# Shadowrocket: 2026-03-07 16:30:13
[General]
bypass-system = true
skip-proxy = *.local, *.crashlytics.com
tun-excluded-routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12

[Rewrite]

# VIP
^https:\/\/api-sub\.meitu\.com\/v2\/user\/vip_info_by_group\.json url script-response-body WinkVip.js
# Credits
^https:\/\/api-sub\.meitu\.com\/v1\/virtual\/account\/balance\.json url script-response-body balance.js
# Coins
^https:\/\/api-wink\.meitumv\.com\/user\/coin_info\.json url script-response-body BizScret.js
# VIP Detail
^https:\/\/api-wink\.meitumv\.com\/user\/vip_detail url script-response-body secretvip.js

[MITM]
hostname = api-sub.meitu.com, api-wink.meitumv.com

[Script]

Wink Full Unlock = type=http-response,pattern=^https:\/\/api-sub\.meitu\.com\/v2\/user\/vip_info_by_group\.json,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/Biguudev/Winkit/refs/heads/main/WinkVip.js
Wink Credits = type=http-response,pattern=^https:\/\/api-sub\.meitu\.com\/v1\/virtual\/account\/balance\.json,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/Biguudev/Winkit/refs/heads/main/balance.js
Wink Coins = type=http-response,pattern=^https:\/\/api-wink\.meitumv\.com\/user\/coin_info\.json,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/Biguudev/Winkit/refs/heads/main/BizScret.js
Wink VIP Detail = type=http-response,pattern=^https:\/\/api-wink\.meitumv\.com\/user\/vip_detail,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/Biguudev/Winkit/refs/heads/main/secretvip.js

hostname =
  api-sub.meitu.com,api-wink.meitumv.com
